In [ ]:
#webcam
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        cv2.imshow("frame", frame)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()


In [9]:
#just show video from sequence
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\SGPtraining\walking_77_image_sequence\img (%d).jpg")

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        cv2.imshow("image", frame)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [3]:
#just show video
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\SGPtraining\DSC_0077.MOV")

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        cv2.imshow("image", frame)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [4]:
#MOG
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\SGPtraining\DSC_0077.MOV")
fgbg = cv2.bgsegm.createBackgroundSubtractorMOG()

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        fgmask = fgbg.apply(frame)
        cv2.imshow('image',fgmask)
        key = cv2.waitKey(30) 
        if key == 27:
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

In [29]:
#MOG2
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\SGPtraining\DSC_0077.MOV")

subtractor = cv2.createBackgroundSubtractorMOG2(history=1000000, varThreshold=5, detectShadows=False)
        
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        mask = subtractor.apply(frame)
        cv2.imshow("image", mask)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [8]:
#Manual
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\SGPtraining\DSC_0077.MOV")
_, first_frame = cap.read()
first_gray = cv2.cvtColor(first_frame, cv2.COLOR_BGR2GRAY)
first_gray = cv2.GaussianBlur(first_gray, (5, 5), 0)
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray_frame = cv2.GaussianBlur(gray_frame, (5, 5), 0)
        difference = cv2.absdiff(first_gray, gray_frame)
        _, difference = cv2.threshold(difference, 25, 255, cv2.THRESH_BINARY)
        cv2.imshow("image", first_frame)
        cv2.imshow("image", frame)
        cv2.imshow("image", difference)
   
        key = cv2.waitKey(30)
        if key == 27:
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.1.0) D:\Build\OpenCV\opencv-4.1.0\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [9]:
#cornor detection normal image
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)

cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\SGPtraining\DSC_0077.MOV")


while(cap.isOpened()):
    ret, frame = cap.read()
    if ret:
        gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        gray = np.float32(gray)
        dst = cv2.cornerHarris(gray,2,3,0.04)
        #result is dilated for marking the corners, not important
        dst = cv2.dilate(dst,None)
        # Threshold for an optimal value, it may vary depending on the image.
        frame[dst>0.01*dst.max()]=[0,0,255]
        cv2.imshow("image", frame)
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [36]:
#webcam detect marker(with highlight level threshold)
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(cap.isOpened()):
    ret, frame, = cap.read()
    if ret:
        imgray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        imblur1 = cv2.medianBlur(imgray,5)
        imblur2 = cv2.GaussianBlur(imblur1,(5,5),0)
        
        ret,thresh = cv2.threshold(imblur2,250,255,cv2.THRESH_BINARY)

        contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

        #print("Number of objects found = ", len(contours))
       
        
        cv2.drawContours(frame, contours, -1, (0,0,255), 10)
        cv2.imshow("frame", frame)
        
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()

In [ ]:
#image edge detection
import cv2
import numpy as np
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
#cv2.resizeWindow('image', 2000,1242)
cv2.resizeWindow('image', 560,996)

img = cv2.imread('BAzmall.jpg',1)
#img = cv2.imread('fap.png',1)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blur = cv2.GaussianBlur(gray,(7,7),0)

canny2 = cv2.Canny(blur, 50, 100)
cv2.imshow("image", canny2)
 

k = cv2.waitKey(0)
if k == 27:         # wait for ESC key to exit
    cv2.destroyAllWindows()

In [ ]:
#show marker coordinate in image
import cv2
import numpy as np
from matplotlib import pyplot as plt

        
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 560,996)
cv2.namedWindow('image2',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image2', 560,996)

img = cv2.imread('FAzmall.jpg')
imgray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imblur1 = cv2.medianBlur(imgray,5)
imblur2 = cv2.GaussianBlur(imblur1,(5,5),0)

ret,thresh = cv2.threshold(imblur2,250,255,cv2.THRESH_BINARY)

contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

print("Number of objects found = ", len(contours))

i = 0
for c in contours:
    # calculate moments for each contour
    M = cv2.moments(c)

    # calculate x,y coordinate of center
    if M["m00"] != 0:
        cX = int(M["m10"] / M["m00"])
        cY = int(M["m01"] / M["m00"])
    else:
        cX = 0
        cY = 0

    i+=1
   # print('\nX',i,' ',cX)
    #print('Y',i,' ',cY)
    centroid = "X"+str(i)+":"+str(cX)+", Y"+str(i)+":"+str(cY)
    cv2.putText(img,centroid , (cX - 25, cY - 25),cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255, 255), 2)

cv2.drawContours(img, contours, -1, (0,0,255), 10)
cv2.imshow("image", img)
cv2.imshow("image2",thresh)


 

k = cv2.waitKey(0)
if k == 27:         # wait for ESC key to exit
    cv2.destroyAllWindows()

In [ ]:
#save video

import cv2
import numpy as np
from matplotlib import pyplot as plt
cv2.namedWindow('image',cv2.WINDOW_NORMAL)
cv2.resizeWindow('image', 1280,720)
cap = cv2.VideoCapture("C:\\Users\sunny.DESKTOP-QGFGEEK\Desktop\SGPtraining\img (%d).jpg")

# Define the codec and create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('77marked.avi',fourcc, 23.9, (1920,1080))

while(cap.isOpened()):
    ret, frame, = cap.read()
    if ret:
        
        #frame = cv2.flip(frame,0)

        # write the flipped frame
        out.write(frame)
        cv2.imshow("image", frame)
        
        key = cv2.waitKey(30)
        if key == 27:
            break
    else: 
        break
cap.release()
cv2.destroyAllWindows()


In [8]:
import cv2
cv2.destroyAllWindows()

In [34]:
#calibrate camera
import numpy as np
import cv2
import glob

# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((7*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:7].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = cv2.VideoCapture(0)

while(images.isOpened()):
    ret, frame = images.read()
    if ret:
        gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        
        # Find the chess board corners
        ret, corners = cv2.findChessboardCorners(gray, (7,7),None)
        
         # If found, add object points, image points (after refining them)
        if ret == True:
            objpoints.append(objp)

            cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
            imgpoints.append(corners)

            # Draw and display the corners
            cv2.drawChessboardCorners(frame, (7,7), corners,ret)
            ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)
        cv2.imshow('frame',frame)    
        key = cv2.waitKey(100)
        if key == 27:
            break
        
    else: 
        break
images.release()
cv2.destroyAllWindows()

np.savez("B.npz", mtx, dist, rvecs, tvecs)

In [39]:
data = np.load("B.npz")

a1 = data['arr_0']
print(a1)
b1 = data['arr_1']
print(b1)
a2 = data['arr_2']
print(a2)
b2 = data['arr_3']
print(b2)
print("==========================================")

print(mtx)
print(dist)
print(rvecs)
print(tvecs)



[[587.29396642   0.         327.04420373]
 [  0.         589.724833   231.75558912]
 [  0.           0.           1.        ]]
[[ 3.82102956e-03  5.10573909e-02  4.93091284e-04 -3.49152720e-05
  -5.08726087e-01]]
[[[ 1.48205349e-01]
  [-7.63150188e-02]
  [ 1.56582859e+00]]

 [[ 1.19532548e-01]
  [ 1.54654932e-02]
  [ 1.58066499e+00]]

 [[ 1.06127910e-01]
  [ 3.10362218e-02]
  [ 1.57074331e+00]]

 [[ 9.67379617e-02]
  [ 2.03633522e-02]
  [ 1.56803438e+00]]

 [[-1.01652738e-01]
  [ 7.14035207e-02]
  [-3.13743441e+00]]

 [[ 7.17700736e-02]
  [ 2.38499721e-02]
  [ 1.57921295e+00]]

 [[ 7.79469273e-02]
  [ 2.26874314e-02]
  [ 1.56313175e+00]]

 [[ 1.03896034e-01]
  [-1.46127828e-01]
  [ 3.13017623e+00]]

 [[ 1.37069546e-01]
  [-7.62443605e-02]
  [ 1.52754670e+00]]

 [[ 5.60804754e-02]
  [-2.23357674e-01]
  [ 3.07369697e+00]]

 [[ 1.20660839e-01]
  [-8.47724445e-02]
  [ 1.52652878e+00]]

 [[ 1.26876127e-01]
  [-7.38443700e-02]
  [ 1.53119808e+00]]

 [[ 1.45559876e-01]
  [-1.94401319e-02]
  [